### PR TITLE
Implement supervisor restart strategies

### PR DESCRIPTION
**Pull request by MarkintoshZ**
Implemented OneForAll strategy for supervisor based on erlang's OPT.
- [x] unit test

I am not sure what these lines of code do. Why would a supervisor receive a kill signal to itself? I tried calling kill on the supervisor but I did not get the panic error message so I wonder if this code is even reachable. Therefore, I took out those lines when I implemented the match branch for OneForAll. Not sure if this is correct.
https://github.com/lunatic-solutions/lunatic-rs/blob/eb55f5fbce04b55c696e1795bc698f5b8dc28e74/src/supervisor.rs#L301-L306

### CODE REVIEW

**Comment by bkolobara** [comment]
I think the message in the `panic!` is not great. It's not triggered on a kill signal, but when a link breaks. A supervisor holds links to children, but the supervisor itself (when started with `start_link`) can be linked to another process. The `else` branch is taken in this case, because the link that broke is not one of the children (tag doesn't exist). It basically kills the supervisor by panicking and all children links are broken, so they will be killed too. This is a way of expressing that the supervisor depends on another process and if this other process fails it doesn't make sense to continue running the supervisor or the children

This also makes the implementation of `OneForAll` a bit tricky. You try to restart all the children that are not the failed link, but you can also link random processes to the supervisor from the outside (`sup.link()`). In case they fail you will also be restarting all the children, even none of them failed.

I think a solution here could be to move the panic check before restarting processes. If the received tag is none of the children panic, if yes continue doing the restarts with the current logic.

Some extra notes:

1. In Erlang, processes are shut down in the opposite order of the start.
2. In Erlang, all processes are first shut down before they are restarted.
3. They are always started in order.

It's not that important for me to have the exact same behaviour in lunatic. First of all, our shutdown method doesn't block until the process is shut down, so it would be hard to even preserve shutdown order. Now that I think about it, I will open a new issue about it as it's useful to block (this would make it also consistent with start, that blocks). And can we even reverse the order of the loop in the macro? The macro rule is a bit limiting here.

**Comment by MarkintoshZ** [comment]
I made a macro for shutting down children in reversed start order so now `terminate` and `restart` will both have the right shutdown order. I also implemented the `RestForOne` strategy and added the corresponding unit test. 

Currently, I am checking the shutdown order manually by using `println!`s but I think it might be good to implement a unit test instead. The problem is that I can't think of any easy way to assert the shutdown order. I thought about having the children log their termination events to a separate logger process but that seems kind of complicated and might make the test code harder to reason about. There is also the problem that messages might not be received out of order. Any ideas?

**Comment by bkolobara** [comment]
This looks awesome and covers **all** strategies that Erlang supports. 🎉 

I think a good way to assert the start/shutdown order is to have a separate process ("logger/assert_order"). This process will be linked to the main one and fail if start/shutdown messages arrive in an unexpected order. To preserve sending order, the logger would be an `AbstractProcess` taking requests. Requests are blocking until the response arrives, this would make the process `terminate` and `init` functions block when calling the logger, and if `start` and `shutdown` are also blocking themselves, the order should be preserved.

**Comment by MarkintoshZ** [comment]
I implemented the logger and it works pretty well. The logger stores the order of `init`, `terminate`, and `panic` calls, and the test process can retrieve the logs and assert them. I wonder if we should keep the assertions using `inc` and `count` requests since the logger provides the same guarantee and even more.

**Comment by bkolobara** [comment]
We can keep them, better to have more assertions if something goes horribly wrong :)

**Comment by MarkintoshZ** [comment]
Sounds good. So is there anything else you want me to change before merging?

**Pull request merged**
